name: Run Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Playwright Docker container
        run: |
          docker build --tag=tah-playwright .

      - name: Run Playwright Docker container
        continue-on-error: true
        id: run-playwright
        run: |
          make test-pw

      - name: Configure S3 Upload Directory
        id: set-directory
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "UPLOAD_DIR=20240727-hackathon/pull/${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          else
            echo "UPLOAD_DIR=20240727-hackathon/main/$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          fi

      - name: Upload Playwright Test Reports
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_S3_BUCKET }}
          source_dir: tests/reports
          destination_dir: ${{ steps.set-directory.outputs.UPLOAD_DIR }}

      - name: Post comments on success
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.run-playwright.outcome == 'success' }}
        with:
          message: |
            Test CompleteðŸŽ‰
            [View Test Result](https://uechan-backet.s3.ap-northeast-1.amazonaws.com/${{ steps.set-directory.outputs.UPLOAD_DIR }}/index.html)

      - name: Post comments on failure
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.run-playwright.outcome == 'failure' }}
        with:
          message: |
            Test FailedðŸ˜­
            [View Test Result](https://uechan-backet.s3.ap-northeast-1.amazonaws.com/${{ steps.set-directory.outputs.UPLOAD_DIR }}/index.html)

      - name: Fail if run-playwright failed
        if: ${{ steps.run-playwright.outcome == 'failure' }}
        run: exit 1
